### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Sat1l** [nemakemake/Laba4#2]
## Luis.java
https://github.com/nemakemake/Laba4/blob/9b3b7bfce2d9bb5da90a553489b440eba91ffc6d/src/table/actors/Luis.java#L10-L13

Почему у человека машина находится в инвентаре? (ещё и по дефолту)

(мнение) Не знаю как это впишется в контекст, но как вариант сделать чтобы где-то это машина стояла (допустим, была на улице/в гараже, как по тексту лучше), и были ключи, которые подходят только к ней

## Group.java
https://github.com/nemakemake/Laba4/blob/9b3b7bfce2d9bb5da90a553489b440eba91ffc6d/src/table/Groups.java#L12-L20

Почему изменение группы меняет персонажей только между внешней и внутренней группой? Это не совсем безопасный подход, тк если чья-то группа будет не та, которая ожидается, то и на выходе будет не та, которая должна быть (пример: как-то не так в течении программы обработали группу персонажа, и за место homegroup он окажется в outgroup, хотя ожидалась homegroup)

(мнение) В редактор группы должен подаваться и Person, и группа, в которую его перекинуть

## Remember.java
https://github.com/nemakemake/Laba4/blob/9b3b7bfce2d9bb5da90a553489b440eba91ffc6d/src/table/actions/Remember.java#L10-L14

Странная работа экшена. Человек вспоминает про предмет и материализует его в свой инвентарь из воздуха? Как вариант, добавить хотя-бы проверку есть ли этот предмет в инвентаре

## Ignoring.java
https://github.com/nemakemake/Laba4/blob/9b3b7bfce2d9bb5da90a553489b440eba91ffc6d/src/table/actions/Ignoring.java#L7-L11

Как тут ignoramus игнорирует speaker? Кроме выведенного текста это ничем не подкреплено. Плюс почему-то итогом работы этого метода всегда будет начало игры, что не хорошо. В итоге под методом "игнорировать" предполагается что ч1 проигнорирует ч2, и ч2 чтобы привлечь внимание начнет игру

## StunningSpeak.java
https://github.com/nemakemake/Laba4/blob/9b3b7bfce2d9bb5da90a553489b440eba91ffc6d/src/table/actions/StunningSpeak.java#L6

Статичную речь которая ставит кого-то в тупик и статичную мысль, над которой кто-то задумывается, надо поменять на переменные которые подаются, иначе любая stunning фраза будет одной и той же, и заставлять задуматься об одном и  том же

**Comment by nemakemake** [comment]
Исправлено
Ссылка на коммит: 48badf0b1b6ee5213b1049d474a7b1392534e4c7

**Comment by Sat1l** [comment]
Все пофикшено, issue закрываю
